---
id: README
title: "storyBASE repo README"
version: 0.1.0
description: "autogenerated readme tracking storyBASE as written"
destination: /
model: 
  - anthropic/claude-sonnet-4.5
  - x-ai/grok-4-fast
  - openai/gpt-4.1-nano
---

### State
Summarize the current state of the storyBASE.

### Stories
Create a section for each story. Summarize the intent of the story, it's relationship to the whole, and a brief summary of how it will be approached from the current storyBASE state. 

### Assets
Briefly summarize the repository structure and a description of each asset, including mermaid charts if appropriate.

### Transactions
Briefly summarize each transaction and its significant to the storyBASE graph, stories, and assets.
